import type { AssetPackConfig, AssetPipe } from "@assetpack/core";
import { path } from "@assetpack/core";
import { pixiPipes } from "@assetpack/core/pixi";
import fs from "node:fs/promises";

const isNativeBuild = !process.env.ROVES_BUILD;

const manifestOutput = "src/assets/manifest.gen.json";

/**
 * AssetPack only creates a manifest bundle for folders explicitly tagged
 * with "{m}" (see pixiManifest's `manifest` tag); everything else lands in
 * the single "default" bundle. This splits the "default" bundle into one
 * bundle per top-level folder under the assets entry, named after that
 * folder, so bundles mirror the folder structure without needing to tag
 * every folder manually. Files directly at the entry root (no folder) stay
 * in "default". Runs after the manifest has been written to disk, so it
 * re-reads and rewrites the file.
 */
function groupBundlesByFolder(options: { output: string }): AssetPipe<{ output: string }> {
    return {
        name: "group-bundles-by-folder",
        defaultOptions: options,
        async finish(_asset, opts) {
            const manifest = JSON.parse(await fs.readFile(opts.output, "utf-8"));

            const bundles = new Map<string, { name: string; assets: unknown[] }>();
            for (const bundle of manifest.bundles) {
                if (bundle.name !== "default") {
                    bundles.set(bundle.name, bundle);
                    continue;
                }
                for (const asset of bundle.assets) {
                    const folder = path.dirname(asset.src[0]).split("/")[0];
                    const bundleName = folder === "." ? "default" : folder;
                    const target = bundles.get(bundleName) ?? { name: bundleName, assets: [] };
                    target.assets.push(asset);
                    bundles.set(bundleName, target);
                }
            }
            manifest.bundles = [...bundles.values()];

            await fs.writeFile(opts.output, JSON.stringify(manifest, null, 2));
        },
    };
}

/**
 * Removes file extensions from the aliases generated by the pixi manifest
 * pipe and replaces path separators with underscores (e.g.
 * "yard/yard1.png" -> "yard_yard1"). Runs after the manifest has been
 * written to disk, so it re-reads and rewrites the file.
 *
 * If two assets end up with the same normalized alias, the later one is
 * prefixed with its bundle name (e.g. "yard_yard_yard1") to keep aliases
 * unique across the whole manifest.
 */
function normalizeAliases(options: { output: string }): AssetPipe<{ output: string }> {
    return {
        name: "normalize-aliases",
        defaultOptions: options,
        async finish(_asset, opts) {
            const manifest = JSON.parse(await fs.readFile(opts.output, "utf-8"));

            const seen = new Set<string>();
            for (const bundle of manifest.bundles) {
                for (const asset of bundle.assets) {
                    asset.alias = asset.alias.map((alias: string) => {
                        const normalized = path.trimExt(alias).replaceAll("/", "_");
                        const unique = seen.has(normalized)
                            ? `${bundle.name}_${normalized}`
                            : normalized;
                        seen.add(normalized);
                        return unique;
                    });
                }
            }

            await fs.writeFile(opts.output, JSON.stringify(manifest, null, 2));
        },
    };
}

const config: AssetPackConfig = {
    entry: "./src/assets",
    output: "./public/assets",
    ignore: ["**/*.ts", "**/*.js", "**/*.gen.*"],
    pipes: [
        ...pixiPipes({
            manifest: {
                output: manifestOutput,
                createShortcuts: true,
            },
            // Native builds: skip @0.5x mipmaps (unused on desktop, WebView/Servo handle DPR)
            resolutions: isNativeBuild ? { default: 1 } : undefined,
            // Native builds: raise WebP quality — files are local so bandwidth is not a concern
            compression: isNativeBuild
                ? { png: true, jpg: true, webp: { quality: 88, alphaQuality: 88 } }
                : undefined,
        }),
        groupBundlesByFolder({ output: manifestOutput }),
        normalizeAliases({ output: manifestOutput }),
    ],
};

export default config;
