/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
import { handleGameWorkerMessage } from "@drincs/pixi-vn/worker";

self.onmessage = async (event) => {
    const response = await handleGameWorkerMessage(event.data);
    if (response) self.postMessage(response);
};
